version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
      day: monday
      time: "03:20"
      timezone: Asia/Bangkok
    allow:
      - dependency-type: direct
