#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


# Zero-cost CI policy: no GitHub-hosted workflow can be introduced accidentally.
workflow_dir = ROOT / ".github" / "workflows"
workflow_files = []
if workflow_dir.exists():
    workflow_files = [p for p in workflow_dir.rglob("*") if p.suffix in {".yml", ".yaml"}]
assert not workflow_files, f"GitHub Actions workflows are forbidden by zero-cost policy: {workflow_files}"

# Dependabot may create only direct npm patch updates from package.json.
dependabot = read(".github/dependabot.yml")
assert len(re.findall(r"^\s*-\s+package-ecosystem:", dependabot, flags=re.M)) == 1
assert re.search(r"^\s*-\s+package-ecosystem:\s*npm\s*$", dependabot, flags=re.M)
assert re.search(r"^\s+directory:\s*/apps/web\s*$", dependabot, flags=re.M)
assert re.search(r"^\s+-\s+dependency-type:\s*direct\s*$", dependabot, flags=re.M)
assert "version-update:semver-minor" in dependabot
assert "version-update:semver-major" in dependabot
for forbidden in ("package-ecosystem: pip", "package-ecosystem: docker", "package-ecosystem: github-actions"):
    assert forbidden not in dependabot, forbidden

package = json.loads(read("apps/web/package.json"))
assert package["version"] == "0.3.0"
for section in ("dependencies", "devDependencies"):
    for name, version in package.get(section, {}).items():
        assert re.fullmatch(r"\d+\.\d+\.\d+", version), f"{name} must be exact x.y.z: {version}"
assert not (ROOT / "apps/web/package-lock.json").exists(), "package-lock.json must not be generated by dependency automation"

# Runtime/container baselines are intentionally frozen. They are updated only by an explicit developer change.
api_dockerfile = read("apps/api/Dockerfile")
web_dockerfile = read("apps/web/Dockerfile")
assert api_dockerfile.startswith("FROM python:3.12.14-slim-bookworm\n")
assert web_dockerfile.count("FROM node:24.19.0-alpine3.24") == 3

compose = read("docker-compose.yml")
expected_images = {
    "postgres:18.6-bookworm",
    "valkey/valkey:8.1.9-alpine3.24",
    "gotenberg/gotenberg:8.34.0",
    "caddy:2.11.4-alpine",
    "chrislusf/seaweedfs:4.44",
    "clamav/clamav:1.5.4",
    "prom/prometheus:v3.13.2",
    "otel/opentelemetry-collector-contrib:0.159.0",
    "ghcr.io/paperless-ngx/paperless-ngx:3.0.5",
}
for image in expected_images:
    assert f"image: {image}" in compose, f"Missing frozen image baseline: {image}"
for floating in ("image: valkey/valkey:8-alpine", "image: caddy:2-alpine", "image: clamav/clamav:stable", ":latest"):
    assert floating not in compose, f"Floating image tag is forbidden: {floating}"

# Release metadata must agree.
assert 'version="0.3.0"' in read("apps/api/app/main.py")
assert "0.3.0 — Phase 3 complete" in read("README.md")
assert "completed Phase 3 baseline" in read("PHASE3.md")
assert "## 0.3.0" in read("CHANGELOG.md")

# User-facing defaults must not recommend known paid cloud services.
for path in ("README.md", "PHASE3.md", "CHANGELOG.md", ".env.example", "docker-compose.yml"):
    text = read(path)
    for term in ("AWS S3", "Grafana Cloud", "Entra ID", "Google Workspace OIDC"):
        assert term not in text, f"Paid-cloud reference {term!r} remains in {path}"

storage = read("apps/api/app/storage.py")
assert "_require_self_hosted_s3_endpoint" in storage
assert "explicit self-hosted PDFHUB_S3_ENDPOINT_URL" in storage

for required in (
    "scripts/validate-free.sh",
    "scripts/validate-direct-dependency.sh",
    "scripts/local-ci-cycle.sh",
    "scripts/local-ci-prs.sh",
    "scripts/local-ci-dependabot.sh",
    "scripts/install-local-ci-user.sh",
    "scripts/uninstall-local-ci-user.sh",
):
    assert (ROOT / required).exists(), f"Missing zero-cost validation component: {required}"

print("release policy: PASS")
