#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CURRENT_RELEASE = "0.5.0"
NEXT_SECURITY_BASELINE = "16.3.3"
PILLOW_MIN = (12, 3, 0)
PILLOW_MAX_EXCLUSIVE = (13, 0, 0)


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def pinned_requirement_version(requirements: str, package: str) -> tuple[int, int, int]:
    match = re.search(
        rf"^{re.escape(package)}==(\d+)\.(\d+)\.(\d+)\s*$",
        requirements,
        flags=re.M,
    )
    assert match, f"{package} must be pinned exactly as x.y.z"
    return tuple(int(part) for part in match.groups())


# Zero-cost CI policy: no GitHub-hosted workflow can be introduced accidentally.
workflow_dir = ROOT / ".github" / "workflows"
workflow_files = []
if workflow_dir.exists():
    workflow_files = [p for p in workflow_dir.rglob("*") if p.suffix in {".yml", ".yaml"}]
assert not workflow_files, f"GitHub Actions workflows are forbidden by zero-cost policy: {workflow_files}"

# Version-update automation remains direct npm patch-only. Security/nonstandard PRs use full validation.
dependabot = read(".github/dependabot.yml")
assert len(re.findall(r"^\s*-\s+package-ecosystem:", dependabot, flags=re.M)) == 1
assert re.search(r"^\s*-\s+package-ecosystem:\s*npm\s*$", dependabot, flags=re.M)
assert re.search(r"^\s+directory:\s*/apps/web\s*$", dependabot, flags=re.M)
assert re.search(r"^\s+-\s+dependency-type:\s*direct\s*$", dependabot, flags=re.M)
assert "version-update:semver-minor" in dependabot
assert "version-update:semver-major" in dependabot
for forbidden in ("package-ecosystem: pip", "package-ecosystem: docker", "package-ecosystem: github-actions"):
    assert forbidden not in dependabot, forbidden

package = json.loads(read("apps/web/package.json"))
assert package["version"] == CURRENT_RELEASE
for section in ("dependencies", "devDependencies"):
    for name, version in package.get(section, {}).items():
        assert re.fullmatch(r"\d+\.\d+\.\d+", version), f"{name} must be exact x.y.z: {version}"
assert package["dependencies"].get("next") == NEXT_SECURITY_BASELINE, "Next.js must remain on the reviewed Phase 5 security baseline"
assert "@playwright/test" in package.get("devDependencies", {}), "Playwright smoke coverage is required"
assert package.get("scripts", {}).get("test:e2e") == "playwright test tests/e2e/pdf-hub.smoke.spec.ts"
assert package.get("scripts", {}).get("test:e2e:stack") == "playwright test tests/e2e/pdf-hub.stack.spec.ts"
for required in (
    "apps/web/playwright.config.ts",
    "apps/web/tests/e2e/pdf-hub.smoke.spec.ts",
    "apps/web/tests/e2e/pdf-hub.stack.spec.ts",
):
    assert (ROOT / required).exists(), f"Missing Phase 5 browser test component: {required}"
assert not (ROOT / "apps/web/package-lock.json").exists(), "package-lock.json must not be generated by dependency automation"

# The mocked browser gate must validate credential propagation, not only the initial login call.
smoke = read("apps/web/tests/e2e/pdf-hub.smoke.spec.ts")
assert "requireApiKey" in smoke
for protected_flow in ("integrations/status", "files?limit=100", "jobs?limit=50", "/preview", "/pdf/compress", "/download"):
    assert protected_flow in smoke, f"Mocked browser smoke is missing protected flow: {protected_flow}"

# Runtime/container baselines are intentionally frozen and changed only by explicit developer review.
requirements = read("apps/api/requirements.txt")
pillow_version = pinned_requirement_version(requirements, "Pillow")
assert PILLOW_MIN <= pillow_version < PILLOW_MAX_EXCLUSIVE, (
    f"Pillow must remain on the reviewed secure 12.x line >= {'.'.join(map(str, PILLOW_MIN))}; "
    f"found {'.'.join(map(str, pillow_version))}"
)
api_dockerfile = read("apps/api/Dockerfile")
web_dockerfile = read("apps/web/Dockerfile")
assert api_dockerfile.startswith("FROM python:3.12.14-slim-bookworm\n")
assert web_dockerfile.count("FROM node:24.19.0-alpine3.24") == 3

compose = read("docker-compose.yml")
expected_images = {
    "postgres:18.6-bookworm",
    "valkey/valkey:8.1.9-alpine3.24",
    "gotenberg/gotenberg:8.34.0",
    "caddy:2.11.4-alpine",
    "chrislusf/seaweedfs:4.44",
    "clamav/clamav:1.5.4",
    "prom/prometheus:v3.13.2",
    "otel/opentelemetry-collector-contrib:0.159.0",
    "ghcr.io/paperless-ngx/paperless-ngx:3.0.5",
}
for image in expected_images:
    assert f"image: {image}" in compose, f"Missing frozen image baseline: {image}"
for floating in ("image: valkey/valkey:8-alpine", "image: caddy:2-alpine", "image: clamav/clamav:stable", ":latest"):
    assert floating not in compose, f"Floating image tag is forbidden: {floating}"
assert 'command: ["python", "-m", "app.webhook_runner"]' in compose
assert "PDFHUB_DOWNLOAD_SIGNING_SECRET" in compose

# Optional management UIs/collectors must not bind to every host interface by default.
management_bind = "${PDFHUB_MANAGEMENT_BIND_HOST:-127.0.0.1}"
for mapping in (
    f'{management_bind}:${{PDFHUB_PROMETHEUS_PORT:-9090}}:9090',
    f'{management_bind}:${{PDFHUB_OTEL_GRPC_PORT:-4317}}:4317',
    f'{management_bind}:${{PDFHUB_OTEL_HTTP_PORT:-4318}}:4318',
    f'{management_bind}:${{PAPERLESS_HTTP_PORT:-8001}}:8000',
):
    assert mapping in compose, f"Management port is not loopback-bound by default: {mapping}"
assert "PDFHUB_MANAGEMENT_BIND_HOST=127.0.0.1" in read(".env.example")

# Phase 5 observability has local alert rules and the Prometheus container actually loads them.
prometheus = read("ops/prometheus/prometheus.yml")
alerts = read("ops/prometheus/alerts.yml")
assert "/etc/prometheus/alerts.yml" in prometheus
assert "./ops/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro" in compose
for alert in ("PdfHubApiDown", "PdfHubHighServerErrorRate", "PdfHubP95LatencyHigh", "PdfHubQueueBacklog", "PdfHubRepeatedJobFailures"):
    assert f"alert: {alert}" in alerts, f"Missing Phase 5 Prometheus alert: {alert}"

# Frontend auth state is protected behaviorally by Playwright. Keep only structural anti-regression checks here.
web_app = read("apps/web/app/components/pdf-hub-app.tsx")
assert "await getMe(value)" in web_app, "Service API key must be validated through auth/me"
assert web_app.index("await getMe(value)") < web_app.index("setAuth(value)"), "Authentication state must be set only after API-key validation"
assert "authenticated && identity ?" in web_app
assert not (ROOT / "apps/web/app/components/pdf-hub-console.tsx").exists(), "Superseded console implementation must stay removed"

# Release metadata must agree while retaining prior completed baselines.
assert f'version="{CURRENT_RELEASE}"' in read("apps/api/app/main.py")
assert f"{CURRENT_RELEASE} — Phase 5 production maturity" in read("README.md")
assert "completed Phase 4 feature baseline" in read("PHASE4.md")
phase5 = read("PHASE5.md")
for section in ("Phase 5A", "Phase 5B", "Phase 5C"):
    assert section in phase5, f"Missing {section} completion documentation"
assert f"## {CURRENT_RELEASE}" in read("CHANGELOG.md")

# Phase 4 feature components remain part of the production foundation.
for required in (
    "apps/api/app/downloads.py",
    "apps/api/app/webhook_runner.py",
    "apps/api/alembic/versions/0003_phase4_webhook_deliveries.py",
    "apps/api/tests/test_downloads.py",
    "apps/api/tests/test_image_conversion.py",
    "apps/api/tests/test_webhook_delivery.py",
):
    assert (ROOT / required).exists(), f"Missing Phase 4 component: {required}"

# Phase 5 operations must be executable repository components, not documentation-only promises.
phase5_ops = (
    "scripts/backup.sh",
    "scripts/verify-backup.sh",
    "scripts/restore.sh",
    "scripts/dr-drill.sh",
    "scripts/load-smoke.py",
    "scripts/release-readiness.sh",
    "scripts/install-backup-user.sh",
    "scripts/uninstall-backup-user.sh",
    "scripts/local-ci-doctor.sh",
)
for required in phase5_ops:
    assert (ROOT / required).exists(), f"Missing Phase 5 operations component: {required}"

backup = read("scripts/backup.sh")
restore = read("scripts/restore.sh")
verify_backup = read("scripts/verify-backup.sh")
assert "pg_dump" in backup and "SHA256SUMS" in backup and "PDFHUB_STORAGE_BACKEND" in backup
assert "PDFHUB_RESTORE_CONFIRM" in restore and "pg_restore" in restore and "FLUSHDB" in restore
assert "sha256sum -c SHA256SUMS" in verify_backup and "PGDMP" in verify_backup

# Zero-cost validation must cover code, browser behavior, operations and the real Compose stack.
for required in (
    "scripts/check-direct-dependency.py",
    "scripts/validate-free.sh",
    "scripts/validate-direct-dependency.sh",
    "scripts/local-ci-cycle.sh",
    "scripts/local-ci-prs.sh",
    "scripts/local-ci-dependabot.sh",
    "scripts/install-local-ci-user.sh",
    "scripts/uninstall-local-ci-user.sh",
):
    assert (ROOT / required).exists(), f"Missing zero-cost validation component: {required}"
validate_free = read("scripts/validate-free.sh")
assert "python3 scripts/validate-release-policy.py" in validate_free
assert "operations()" in validate_free
assert "npm run test:e2e:stack" in validate_free
assert "Pillow==" not in validate_free, "Dependency policy must not be duplicated in validate-free.sh"

validate_direct = read("scripts/validate-direct-dependency.sh")
assert 'python3 scripts/check-direct-dependency.py "${BASE_REF}" HEAD' in validate_direct
assert "npm run test:e2e" in validate_direct, "Direct npm patches must pass browser smoke"

local_ci_prs = read("scripts/local-ci-prs.sh")
local_ci_dependabot = read("scripts/local-ci-dependabot.sh")
local_ci_cycle = read("scripts/local-ci-cycle.sh")
local_ci_install = read("scripts/install-local-ci-user.sh")
assert "local-ci/validate-free" in local_ci_prs
assert "base is stale" in local_ci_prs
assert "local-ci/dependency" in local_ci_dependabot
assert "validate-direct-dependency.sh" in local_ci_dependabot
assert "gh auth status" in local_ci_cycle
assert "gh auth status" in local_ci_install

# User-facing defaults must not recommend known paid cloud services.
for path in ("README.md", "PHASE3.md", "PHASE4.md", "PHASE5.md", "CHANGELOG.md", "VALIDATION.md", ".env.example", "docker-compose.yml"):
    text = read(path)
    for term in ("AWS S3", "Grafana Cloud", "Entra ID", "Google Workspace OIDC"):
        assert term not in text, f"Paid-cloud reference {term!r} remains in {path}"

storage = read("apps/api/app/storage.py")
assert "_require_self_hosted_s3_endpoint" in storage
assert "explicit self-hosted PDFHUB_S3_ENDPOINT_URL" in storage

print("release policy: PASS")
